apiVersion: v1
kind: Service
metadata:
  name: vsocial-backend-service
spec:
  selector:
    app: vsocial-backend
  ports:
    - protocol: TCP
      port: 5454
      targetPort: 5454
  type: LoadBalancer
