apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsocial-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vsocial-frontend
  template:
    metadata:
      labels:
        app: vsocial-frontend
    spec:
      containers:
        - name: vsocial-frontend
          image: vaibhav990/vsocial-frontend
          ports:
            - containerPort: 80
